[package]
name = "sleep-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
pinscher = { git = "https://github.com/jeandiegof/pinscher", tag = "0.1.0"}
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.1.18", features = ["derive"] }